name: evolutin_game
on:
  push:
    branches:
      - 'development_phase'
      - 'new_feeding_phase'
      - 'base_feeding_phase'

jobs:
  clang-format:
    runs-on: Ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - run: clang-format --version
      - run: for file in $(find . -iname '*.cpp' -or -iname '*.h' -and -not -iname 'doctest.h' ); do diff -u <(cat "$file") <(clang-format "$file") || exit 1; done
  clang-tidy:
    runs-on: Ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - run: clang-tidy --version
      - run: clang-tidy $(find . -path '*/CMakeFiles/*' -prune -or \( -iname '*.cpp' -or -iname '*.h' -and -not -iname 'doctest.h' \) -print)
  steps:
    - uses: actions/checkout@v2
    - run: cmake --version
    - run: cmake .
    - run: make